function y = doFilter(x)
%DOFILTER 입력값 x를 필터링하여 출력값 y를 반환합니다.

% MATLAB Code
% Generated by MATLAB(R) 9.6 and DSP System Toolbox 9.8.
% Generated on: 19-Nov-2019 22:02:23

%#codegen

% 이 함수에서 C/C++ 코드를 생성하려면 codegen 명령을 사용하십시오. 자세한 내용을 보려면 'help codegen'을
% 입력하십시오.

persistent Hd;

if isempty(Hd)
    
    % 필터 계수를 설계하는 데 사용된 코드는 다음과 같습니다.
    %
    % N    = 2;        % Order
    % F3dB = 0.39789;  % 3-dB Frequency
    % Fs   = 100;      % Sampling Frequency
    %
    % h = fdesign.lowpass('n,f3db', N, F3dB, Fs);
    %
    % Hd = design(h, 'butter', ...
    %     'SystemObject', true);
    
    Hd = dsp.BiquadFilter( ...
        'Structure', 'Direct form II', ...
        'SOSMatrix', [1 2 1 1 -1.96464824772332 0.965262360224868], ...
        'ScaleValues', [0.000153528125386148; 1]);
end

s = double(x);
y = step(Hd,s);

